2024-01-09 14:45:08 | ERROR | la columna «users.id_user» debe aparecer en la cláusula GROUP BY o ser usada en una función de agregación
LINE 2:                 SELECT posts.*, users.id_user, users.name, u...
                                        ^

2024-01-09 14:45:08 | ERROR | Traceback (most recent call last):
  File "C:\Users\bloos\OneDrive\Documentos\Programacion\Proyectos\BPPFP\src\models\PostModel.py", line 119, in get_relevant_posts
    self.cursor.execute(select_query)
psycopg2.errors.GroupingError: la columna «users.id_user» debe aparecer en la cláusula GROUP BY o ser usada en una función de agregación
LINE 2:                 SELECT posts.*, users.id_user, users.name, u...
                                        ^


